version: '3'
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./schema-prod.sql:/docker-entrypoint-initdb.d/schema-prod.sql
  discovery:
    container_name: discovery
    restart: always
    build: ./discovery
    ports:
      - "3000:3000"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
  config-server:
    container_name: config-server
    restart: always
    build: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    volumes:
      - /root/config-properties:/config
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "8081:8081"
    depends_on:
      - discovery
      - config-server
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    entrypoint: ./gateway-entrypoint.sh config-server 8888 java -jar /app/gateway.jar
  admins:
    container_name: admins
    restart: always
    build: ./admins
    ports:
      - "8083:8083"
    depends_on:
      - discovery
      - config-server
      - gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    entrypoint: ./admins-entrypoint.sh config-server 8888 java -jar /app/admins.jar
  emails:
    container_name: emails
    restart: always
    build: ./emails
    ports:
      - "8087:8087"
    depends_on:
      - discovery
      - config-server
      - gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    entrypoint: ./emails-entrypoint.sh config-server 8888 java -jar /app/emails.jar
  monitoring:
    container_name: monitoring
    restart: always
    build: ./monitoring
    ports:
      - "3032:3032"
    depends_on:
      - discovery
      - config-server
      - gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    entrypoint: ./monitoring-entrypoint.sh config-server 8888 java -jar /app/monitoring.jar
  orders:
    container_name: orders
    restart: always
    build: ./orders
    ports:
      - "8086:8086"
    depends_on:
      - discovery
      - config-server
      - gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    entrypoint: ./orders-entrypoint.sh config-server 8888 java -jar /app/orders.jar
  products:
    container_name: products
    restart: always
    build: ./products
    ports:
      - "8085:8085"
    depends_on:
      - discovery
      - config-server
      - gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    entrypoint: ./products-entrypoint.sh config-server 8888 java -jar /app/products.jar
  users-center:
    container_name: users-center
    restart: always
    build: ./users-center
    ports:
      - "8082:8082"
    depends_on:
      - discovery
      - config-server
      - gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    entrypoint: ./users-center-entrypoint.sh config-server 8888 java -jar /app/users-center.jar
  websocket:
    container_name: websocket
    restart: always
    build: ./websocket
    ports:
      - "8094:8094"
    depends_on:
      - discovery
      - config-server
      - gateway
      - orders-service
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    entrypoint: ./websocket-entrypoint.sh config-server 8888 java -jar /app/websocket.jar
  statistics:
    container_name: statistics
    restart: always
    build: ./statistics
    ports:
      - "8089:8089"
    depends_on:
      - postgresdb
      - discovery
    environment:
      - "ENVIRONMENT=prod"
    entrypoint: ./statistics-entrypoint.sh postgresdb 5432 discovery 3000 statistics
  managers:
    container_name: managers
    restart: always
    build: ./managers
    ports:
      - "8084:8084"
    depends_on:
      - postgresdb
      - discovery
    environment:
      - "ENVIRONMENT=prod"
    entrypoint: ./managers-entrypoint.sh postgresdb 5432 discovery 3000 managers