version: '3'
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./schema-default.sql:/docker-entrypoint-initdb.d/schema-default.sql
  server-mock:
    container_name: server-mock
    build: ./server-mock
    ports:
      - "2222:2222"