version: '3'
services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: orders_default.db,products_default.db,users_default.db
  discovery:
    container_name: discovery
    build: ./discovery
    ports:
      - "3001:3001"
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
  config-server:
    container_name: config-server
    build: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
  gateway:
    container_name: gateway
    build: ./gateway
    ports:
      - "8081:8081"
    depends_on:
      - discovery
      - config-server
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
  admins:
    container_name: admins
    build: ./admins
    ports:
      - "8585:8585"
    depends_on:
      - discovery
      - config-server
      - gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
  emails:
    container_name: emails
    build: ./emails
    ports:
      - "8689:8689"
    depends_on:
      - discovery
      - config-server
      - gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
  monitoring:
    container_name: monitoring
    build: ./monitoring
    ports:
      - "8281:8281"
    depends_on:
      - discovery
      - config-server
      - gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
  orders-service:
    container_name: orders-service
    build: ./orders
    ports:
      - "8687:8687"
    depends_on:
      - discovery
      - config-server
      - gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
  products-service:
    container_name: products-service
    build: ./products
    ports:
      - "8686:8686"
    depends_on:
      - discovery
      - config-server
      - gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
  users-center:
    container_name: users-center
    build: ./users-center
    ports:
      - "8587:8587"
    depends_on:
      - discovery
      - config-server
      - gateway
    environment:
      - "SPRING_PROFILES_ACTIVE=default"
  websocket:
    container_name: websocket
    build: ./websocket
    ports:
      - "8187:8187"
    depends_on:
      - discovery
      - config-server
      - gateway
      - orders-service
    environment:
      - "SPRING_PROFILES_ACTIVE=default"